modbustcp:
  - id: modbustesttcp
    host: 192.168.178.46
    port: 502
    
modbustcp_controller:
  - id: modbus_device
    modbustcp_id: modbustesttcp
    address: 1
    update_interval: 1s

sensor:

  # Phase A
  
  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-Voltage
    address: 1021
    value_type: FP32  
    register_type: read
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-Current
    address: 1023
    value_type: FP32  
    register_type: read
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"
    accuracy_decimals: 2
  
  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-active-Power
    address: 1025
    value_type: FP32  
    register_type: read
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-apparent-Power
    address: 1027
    value_type: FP32  
    register_type: read
    unit_of_measurement: "VA"
    device_class: "apparent_power"
    state_class: "measurement"
    accuracy_decimals: 2

  
  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-Frequency
    address: 1034
    value_type: FP32  
    register_type: read
    unit_of_measurement: "Hz"
    device_class: "frequency"
    state_class: "measurement"
    accuracy_decimals: 2
  

## Phase B

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: B-Voltage
    address: 1041
    value_type: FP32  
    register_type: read
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2


 ## Phase C

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: C-Voltage
    address: 1061
    value_type: FP32  
    register_type: read
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2
