external_components:
  - source: github://creepystefan/esphome_tcp
    refresh: 0s

modbustcp:
  - id: modbustesttcp
    host: 192.168.178.46
    port: 502
    
modbustcp_controller:
  - id: modbus_device
    modbustcp_id: modbustesttcp
    address: 1
    update_interval: 1s

sensor:
  ## Total

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: Total-Current
    address: 1012
    value_type: FP32  
    register_type: read
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: Total-active-Power
    address: 1014
    value_type: FP32  
    register_type: read
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: Total-apparent-Power
    address: 1016
    value_type: FP32  
    register_type: read
    unit_of_measurement: "VA"
    device_class: "apparent_power"
    state_class: "measurement"
    accuracy_decimals: 2

  ## Phase A
  
  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-Voltage
    address: 1021
    value_type: FP32  
    register_type: read
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-Current
    address: 1023
    value_type: FP32  
    register_type: read
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"
    accuracy_decimals: 2
  
  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-active-Power
    address: 1025
    value_type: FP32  
    register_type: read
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-apparent-Power
    address: 1027
    value_type: FP32  
    register_type: read
    unit_of_measurement: "VA"
    device_class: "apparent_power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-Power-Factor
    address: 1029
    value_type: FP32  
    register_type: read
    unit_of_measurement: "%"
    device_class: "power_factor"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: A-Frequency
    address: 1034
    value_type: FP32  
    register_type: read
    unit_of_measurement: "Hz"
    device_class: "frequency"
    state_class: "measurement"
    accuracy_decimals: 2
  

## Phase B

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: B-Voltage
    address: 1041
    value_type: FP32  
    register_type: read
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: B-Current
    address: 1043
    value_type: FP32  
    register_type: read
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"
    accuracy_decimals: 2
  
  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: B-active-Power
    address: 1045
    value_type: FP32  
    register_type: read
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: B-apparent-Power
    address: 1047
    value_type: FP32  
    register_type: read
    unit_of_measurement: "VA"
    device_class: "apparent_power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: B-Power-Factor
    address: 1049
    value_type: FP32  
    register_type: read
    unit_of_measurement: "%"
    device_class: "power_factor"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: B-Frequency
    address: 1054
    value_type: FP32  
    register_type: read
    unit_of_measurement: "Hz"
    device_class: "frequency"
    state_class: "measurement"
    accuracy_decimals: 2

 ## Phase C

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: C-Voltage
    address: 1061
    value_type: FP32  
    register_type: read
    unit_of_measurement: "V"
    device_class: "voltage"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: C-Current
    address: 1063
    value_type: FP32  
    register_type: read
    unit_of_measurement: "A"
    device_class: "current"
    state_class: "measurement"
    accuracy_decimals: 2
  
  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: C-active-Power
    address: 1065
    value_type: FP32  
    register_type: read
    unit_of_measurement: "W"
    device_class: "power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: C-apparent-Power
    address: 1067
    value_type: FP32  
    register_type: read
    unit_of_measurement: "VA"
    device_class: "apparent_power"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: C-Power-Factor
    address: 1069
    value_type: FP32  
    register_type: read
    unit_of_measurement: "%"
    device_class: "power_factor"
    state_class: "measurement"
    accuracy_decimals: 2

  - platform: modbustcp_controller
    modbustcp_controller_id: modbus_device
    name: C-Frequency
    address: 1074
    value_type: FP32  
    register_type: read
    unit_of_measurement: "Hz"
    device_class: "frequency"
    state_class: "measurement"
    accuracy_decimals: 2
