substitutions:
  ShellyIP: "HERE IP FROM SHELLY" 
  interval: "1s"  ## Interval Time for Request
  
http_request:
  useragent: esphome/device
  timeout: 5s
  id: getrequest

interval:
  - interval: ${interval}
    then:
      - http_request.get:
          url: http://${ShellyIP}/rpc/Shelly.GetStatus
          verify_ssl: false
          headers:
            Content-Type: application/json
          on_response:
            then:
              - lambda: |-
                  json::parse_json(id(getrequest).get_string(), [](JsonObject root) {
                      id(total_act_power).publish_state(root["em:0"]["total_act_power"]);
                  });

sensor:
  - platform: template
    name: total_act_power
    id: total_act_power
