substitutions:
  ShellyIP: "HERE IP FROM SHELLY" 
  interval: "1s"  ## Interval Time for Request
  
http_request:
  useragent: esphome/device
  timeout: 5s
  id: getrequest
  verify_ssl: false

#######      NEED Interval.yaml

sensor:
  - platform: template
    name: ID
    id: id
    
  - platform: template
    name: a_voltage
    id: a_voltage

  - platform: template
    name: b_voltage
    id: b_voltage

  - platform: template
    name: c_voltage
    id: c_voltage

  - platform: template
    name: a_freq
    id: a_voltage

  - platform: template
    name: b_freq
    id: b_freq

  - platform: template
    name: c_freq
    id: c_freq
