esphome:
  name: shelly_modbus_tcp
  platform: ESP32
  board: esp32dev
  includes:
    - modbus_tcp_shelly.h

wifi:
  ssid: "your_wifi_ssid"
  password: "your_wifi_password"

logger:
  level: DEBUG  # Enable debug-level logs to see raw data in the ESPHome logs

# Web Server for Monitoring
web_server:
  port: 80

# Modbus Sensors Configuration
sensor:
  - platform: custom
    lambda: |-
      auto host = "192.168.178.46";
      auto port = 502;

      // Add sensors with custom update intervals
      auto a_voltage = new ModbusTCPSensor(host, port, 4, "AB_CD", 15000);  // 15s interval
      App.register_component(a_voltage);
      a_voltage->set_name("A-Voltage (V)");

      auto b_voltage = new ModbusTCPSensor(host, port, 4, "AB_CD", 15000);  // 15s interval
      App.register_component(b_voltage);
      b_voltage->set_name("B-Voltage (V)");
      
      
      return {a_voltage, b_voltage};
    sensors:
      - name: "A-Voltage (V)"
      - name: "B-Voltage (V)"
      
ota:
